---
title: Octocat's homepage
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
theme: jekyll-theme-minimal
description: Bookmark this to keep an eye on my project updates!
