---
title: Test Brand Book
timezone: Europe/London
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Bookmark this to keep an eye on my project updates!
